import euler from "./euler"
import squeeth_by_opyn from "./squeeth_by_opyn"
import tempus_finance from "./tempus_finance"

export type CoveredProtocolMeta = {
  bytesIdentifier: string
  tag: string
  name?: string
  website?: string
  logo?: string
  description?: string
  agreement?: string
  agreement_hash?: string
  agent?: string
  pay_year?: string
  pay_contracts?: string
}

type CoveredProtocolsMetas = {
  [key: string]: CoveredProtocolMeta
}

const coveredProtocolMetas: CoveredProtocolsMetas = {
  [euler.bytesIdentifier]: euler,
  [squeeth_by_opyn.bytesIdentifier]: squeeth_by_opyn,
  [tempus_finance.bytesIdentifier]: tempus_finance,
  "0x4652414e00000000000000000000000000000000000000000000000000000000": {
    bytesIdentifier: "0x4652414e00000000000000000000000000000000000000000000000000000000",
    tag: "fran",
    name: "Fran test protocol",
    website: "https://tempus.finance/",
    logo: "",
    description:
      "Tempus is a multi-chain fixed-income protocol that integrates with lending protocols, staking protocols, and yield aggregators, and lets users fix or speculate on the yield generated by them.",
    agreement: "https://v1.sherlock.xyz/static/pdf/Tempus_Statement_of_Coverage.pdf",
    agreement_hash: "0x4222be442d853bca3663c7984f475d271344fb9a4aff2145406f1939a439b275",
    agent: "0xDA3ec2E372c4DcbDB07c3157Bae438BcC11de25D",
    pay_year: "$123,200.00",
    pay_contracts: "3907",
  },
}

export default coveredProtocolMetas
