import { CoveredProtocolMeta } from "./index"

const meta: CoveredProtocolMeta = {
  id: "0x615307f589ff909e3b7cfbf4d4b4371eb99fa64353970d40b76c1c37381e5cf0",
  tag: "tempus",
  name: "Tempus Finance",
  website: "https://tempus.finance/",
  logo: "",
  description:
    "Tempus is a multi-chain fixed-income protocol that integrates with lending protocols, staking protocols, and yield aggregators, and lets users fix or speculate on the yield generated by them.",
  agreement: "https://v1.sherlock.xyz/static/pdf/Tempus_Statement_of_Coverage.pdf",
  agreement_hash: "0x4222be442d853bca3663c7984f475d271344fb9a4aff2145406f1939a439b275",
  agent: "0xab40a7e3cef4afb323ce23b6565012ac7c76bfef",
  pay_year: "$123,200.00",
  pay_contracts: "3907",
}

export default meta
